server:
  ssl:
    enabled: true
    key-store: classpath:keystore.p12
    key-store-password: password
    key-store-type: PKCS12
    
eureka:
  instance:
    prefer-ip-address: true
    nonSecurePortEnabled: false
    securePortEnabled: true
    statusPageUrl: 'https://${eureka.hostname}:${server.port}/actuator/info'
    healthCheckUrl: 'https://${eureka.hostname}:${server.port}/actuator/health'
    homePageUrl: 'https://${eureka.hostname}:${server.port}/'
  client:
    service-url:
      defaultZone: 'https://localhost:8761/eureka'
    tls:
      enabled: true
      key-store: classpath:keystore.p12
      key-store-type: PKCS12
      key-store-password: password
      key-password: password
      trust-store: classpath:truststore.p12
      trust-store-type: PKCS12
      trust-store-password: password