server:
  port: 8082

spring:
  application:
    name: core
  profiles:
    active:
    - development
    
management:
  endpoints:
    web:
      exposure:
        include: 
          - "*"
  endpoint:
    env:
      show-values: always
    health:
      show-details: always
    
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/